spring:
  profiles:
    active: dev
logging:
  config: classpath:logback-spring.xml
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always